<?php
/**
 * 模块菜单
 * 字段说明
 * url 【链接地址】格式：member/控制器/方法，可填写完整外链[必须以http开头]
 * param 【扩展参数】格式：a=123&b=234555
 */
return [
    [
        'pid'           => 0,
        'is_menu'       => '1',
        'title'         => '会员中心',
        'icon'          => '',
        'module'        => 'member',
        'url'           => 'member/index/',
        'param'         => '',
        'target'        => '_self',
        'nav'           => 1,
        'sort'          => 100,
        'childs'         => [
            [
                'title' => '会员列表',
                'icon' => 'fa fa-credit-card',
                'module' => 'member',
                'url' => 'member/index/index',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
                'childs' => [
                    [
                    'title' => '编辑',
                    'icon' => 'fa fa-credit-card',
                    'module' => 'member',
                    'url' => 'member/index/edit',
                    'param' => '',
                    'target' => '_self',
                    'debug' => 0,
                    'system' => 0,
                    'nav' => 0,
                    'sort' => 0,
                    ],
                    [
                    'title' => '删除',
                    'icon' => 'fa fa-credit-card',
                    'module' => 'member',
                    'url' => 'member/index/del',
                    'param' => '',
                    'target' => '_self',
                    'debug' => 0,
                    'system' => 0,
                    'nav' => 0,
                    'sort' => 0,
                    ],
                    [
                    'title' => '明细',
                    'icon' => 'fa fa-credit-card',
                    'module' => 'member',
                    'url' => 'member/account/index',
                    'param' => '',
                    'target' => '_self',
                    'debug' => 0,
                    'system' => 0,
                    'nav' => 0,
                    'sort' => 0,
                    ],
                    [
                    'title' => '状态',
                    'icon' => 'fa fa-credit-card',
                    'module' => 'member',
                    'url' => 'member/index/status',
                    'param' => '',
                    'target' => '_self',
                    'debug' => 0,
                    'system' => 0,
                    'nav' => 0,
                    'sort' => 0,
                    ],
                    [
                    'title' => '重置密码',
                    'icon' => 'fa fa-credit-card',
                    'module' => 'member',
                    'url' => 'member/index/modify_pwd',
                    'param' => '',
                    'target' => '_self',
                    'debug' => 0,
                    'system' => 0,
                    'nav' => 0,
                    'sort' => 0,
                    ],
                    [
                    'title' => '修改帐户',
                    'icon' => 'fa fa-credit-card',
                    'module' => 'member',
                    'url' => 'member/index/modify_account',
                    'param' => '',
                    'target' => '_self',
                    'debug' => 0,
                    'system' => 0,
                    'nav' => 0,
                    'sort' => 0,
                    ],
                ],
            ],
            [
                'title' => '会员等级',
                'icon' => 'fa fa-credit-card',
                'module' => 'member',
                'url' => 'member/level/index',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
                'childs' => [
                     [
                    'title' => '编辑',
                    'icon' => 'fa fa-credit-card',
                    'module' => 'member',
                    'url' => 'member/level/edit',
                    'param' => '',
                    'target' => '_self',
                    'debug' => 0,
                    'system' => 0,
                    'nav' => 0,
                    'sort' => 0,
                    ],
                    [
                    'title' => '删除',
                    'icon' => 'fa fa-credit-card',
                    'module' => 'member',
                    'url' => 'member/level/del',
                    'param' => '',
                    'target' => '_self',
                    'debug' => 0,
                    'system' => 0,
                    'nav' => 0,
                    'sort' => 0,
                    ],
                ],
            ],
            [
                'title' => '会员文件',
                'icon' => 'fa fa-credit-card',
                'module' => 'member',
                'url' => 'member/member_file/index',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
            ],
        ]
    ],
];