<?php
return [
  [
    'title' => '新闻公告',
    'is_menu' => 1,
    'icon' => 'el-icon-postcard',
    'module' => 'news',
    'url' => 'news',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 0,
    'nav' => 1,
    'sort' => 100,
    'childs' => [
      [
        'title' => '新闻列表',
        'icon' => 'aicon ai-caidan',
        'module' => 'news',
        'url' => 'news/index/index',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '增加',
            'icon' => 'aicon ai-tianjia',
            'module' => 'news',
            'url' => 'news/index/add',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 0,
            'sort' => 0,
          ],
          [
            'title' => '编辑',
            'icon' => 'aicon ai-error',
            'module' => 'news',
            'url' => 'news/index/edit',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 0,
            'sort' => 0,
          ],
          [
            'title' => '删除',
            'icon' => 'aicon ai-jinyong',
            'module' => 'news',
            'url' => 'news/index/del',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 0,
            'sort' => 0,
          ],
        ],
      ],
      [
        'title' => '公告',
        'icon' => 'aicon ai-caidan',
        'module' => 'news',
        'url' => 'news/msg/index',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '增加',
            'icon' => 'aicon ai-tianjia',
            'module' => 'news',
            'url' => 'news/msg/add',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 0,
            'sort' => 0,
          ],
          [
            'title' => '编辑',
            'icon' => 'aicon ai-error',
            'module' => 'news',
            'url' => 'news/msg/edit',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 0,
            'sort' => 0,
          ],
          [
            'title' => '删除',
            'icon' => 'aicon ai-jinyong',
            'module' => 'news',
            'url' => 'news/msg/del',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 0,
            'sort' => 0,
          ],
        ],
      ],
    ],
  ],
];
